### ISSUE TITLE
About "use_intra_process_comms" can't work

### ISSUE THREAD

**Issue by dongxuanlb** [intel/ros2_openvino_toolkit#178]
Hi
in the robot_devkit branch, when I run rs_od file, it gives me :

[INFO] [realsense_node-1]: process started with pid [47019]
[realsense_node-1] [INFO] [camera]: Device with serial number 837212070949 was found.
[realsense_node-1] [INFO] [camera]: Create a node for D435i Camera
[realsense_node-1] terminate called after throwing an instance of 'std::invalid_argument'
[realsense_node-1]   what():  **_intraprocess communication allowed only with volatile durability_**
[ERROR] [realsense_node-1]: process has died [pid 47019, exit code -6, cmd '/home/dongxuan/dev_ws/install/realsense_node/lib/realsense_node/realsense_node --ros-args --params-file /tmp/launch_params_k0e9tlse'].

my ros2 version is eloquent.

**Comment by LewisLiuPub** [comment]
@dongxuanlb Yes, you are right. We have found this issue, and have made a workaround to fix it, (see [this patch](https://github.com/intel/ros2_openvino_toolkit/pull/176/commits/0c65c95ef0d03d142436d484d8f2a4f7e2ba4e72).)
In order to support version eloquent, I created branch eloquent for the eloquent related bug fixing. So currently please use **branch "eloquent"**. I will merge the latest commits back to Branch Devel and Master once they are verified by our testers.
