### ISSUE TITLE
Instructions are in wrong order?

### ISSUE THREAD

**Issue by mattcurf** [intel/ros2_openvino_toolkit#5]
Instructions have us installing librealsense first (which modifies the uvcvideo.ko driver of the installed kernel) then has installing the OpenVINO second (which asks us to upgrade to a 4.14 kernel).  Doesn't this break/revert the patched librealsense uvcvideo.ko driver?

**Comment by LewisLiuPub** [comment]
@mattcurf 
Actually, by following the steps you mentioned, there are risks making librealsense related driver installation reverted.
It is not mandatory to upgrade kernel when installing OpenVINO, you may just skip the kernel upgrading, as we always do. It would be safer to install librealsense after you upgrade kernel.

I will add notes in the README file, in order to get rid of the confusion.  Thank you very much!
